version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=berbo
      - MONGO_INITDB_ROOT_PASSWORD=myyPass
    volumes:
      - mongodb:/data/db

  redis:
    image: redis

volumes:
  mongodb:
